promise篇章1

本篇开始回顾下ES6中的`Promise`。注意是回顾，如果想从基础看promise的话，推荐看阮一峰大神的ES6入门中的promise章节。

在这个API面世之前，js开发者写异步代码主要用的是“回调函数”。但回调地狱什么的，想必有过经历都懂，难写难看难维护，真是不想看第二眼。所以`Promise`出来后备受欢迎。

当我下决心并把`Promise`真正弄懂之后，恨不得抱着`Promise`亲两口，把垃圾的回调一脚踢到天涯海角去，唔，那种心情想必有过经历的也懂，哈哈~~~

在开始看`Promise`代码之前，先拿一个实际生活案例来对`Promise`运行机制有个初步印象：

>和妹子去餐厅吃牛排，找到位子坐下来后第一件事就是拿菜单点单，唔，这个这个那个一顿乱戳，选好菜品呼叫服务生确认菜单，服务生确认后去开单然后把菜品账单拿回来给你，告知20分钟内所有菜品将上齐，请耐心等待。点菜就是一个请求的过程，菜品账单就是一个承诺，保证最终会得到那些菜。所以得保存好菜品账单，这代表未来的菜品，所以此时无需担心。在等菜的过程中你可以和妹子在位子上讲话增进感情了。你对那些菜已经抱有想象，味道咋样？妹子喜不喜欢吃？价钱划不划算？菜虽然还上来但你已有这些想法，依据是大脑已经把菜品账单当作菜品的占位符，从本质上讲，这个占位符使得值不再依赖时间，这是一个未来值。终于服务生上菜了，上完菜就是一个承诺值完成的过程。当然也有可能会出现另一种情况，服务生抱歉的告诉你某样菜没有了，此时除了失望、愤怒，但还应看到未来值的另一个重要特性：它可能成功，也可能失败。

基于上例理解，`Promise`就是一个未来值承诺会执行的过程，不管这个未来值是成功还是失败。

下面给出Primise的一个使用实例。

```javascript
function add(xPromise, yPromise) {
    // Promise.call([..])接收一个promise数组并返回一个新的promise
    // 这个返回的新promise等待数组中的所有promise完成
    return Promise.all([xPromise, yPromise])
}

var xPromise = function () {
    return new Promise(function (resolve, reject) {
                var str = "hello";
                setTimeout(function () {
                    if(str){
                        resolve(str);
                    }else {
                        reject("str is undefined.");
                    }
                }, 1000)
            })
            .then(function (res) {
                return res;
            })
            .catch(function (err) {
                console.log(err);
            })
}

var yPromise = function () {
    return new Promise(function (resolve, reject) {
                var str = "world";
                setTimeout(function () {
                    if(str){
                        resolve(str);
                    }else {
                        reject("str is undefined.");
                    }
                }, 2000)
            })
            .then(function (res) {
                return res;
            })
            .catch(function (err) {
                console.log(err);
            })
}

// xPromise()和yPromise()返回相应值的promise，可能已经就绪，也可能以后就绪
add( xPromise(), yPromise() )
// add函数返回的promise决议后，取得收到的x值和y值加在一起
.then(function (valArr) {
    console.log(valArr);
    return valArr[0] + " " + valArr[1];
})
// 得到一个两个数组的和的promise，继续链式调用then()来等待返回新的promise
.then(function (sum) {
    console.log(sum);
})
```
xPromise()和yPromise()是直接调用的，它们的返回值(是promise)被传给add()，第二层是add()，通过`Promise.all([..])`创建并返回的promise，通过调用then()来等待这个promise。

就像上面的点菜案例一样，Promise决议的结果可能是完成也可能是拒绝。拒绝值和完成的Promise不一样：完成值总是编程给出，而拒绝值，也叫拒绝原因(reject reason)则可能是程序逻辑直接设置的，也可能是从运行异常隐式得出的值。

通过Promise，调用then()实际上可以接收两个函数参数，第一个是用于完成情况，第二个是用于拒绝情况：
```javascript
add( xPromise(), yPromise() )
.then(
    //完成处理函数
    function (sum) {
        console.log(sum);
    },
    //拒绝处理函数
    function (err) {
        console.log(err);
    },
)
```
但通常的写法是把拒绝原因写在最后统一的catch中，而不写在then()里面。

关于promise有一个设计中最基础也是最重要的因素，promise决议后就是外部不可变的值，可以安全的把这个值传递给第三方，并确信它不会被有意无意的修改。

promise是一种封装和组合未来值的易于复用的机制。

----------------------------------------------------------------------------------------------------------------

在使用`Promise`时，一个很重要的细节是如何确定值是不是真正的Promise，或者说它是不是一个行为方式类似于Promise的值？

一种检测方法是基于认为既然Promise是通过`new Promise(...)`创建的，那就可以通过`p instanceof Promise`来检查，但事实上这不足以作为检测方法。

原因很多，最主要的是Promise值可能是从其他浏览器窗口(iframe等)接收到的。这个浏览器窗口自己的Promise可能和当前窗口/frame的不同，所以这样的检查是无法识别Promise实例的。另外，有些库或者框架也有可能会选择实现自己的Promise，而不是使用原生的ES6 Promise来实现。

识别Promise(或者行为类似于Promise的东西)就是定义某种被称为thenable的东西，将其定义为任何具有then()方法的对象和函数，我们认为，任何这样的值就是Promise一致的thenable。

比较好的识别方法是通过鸭子类型检查来判断是否为Promise值。即根据一个值的形态(具有哪些属性)对这个值的类型做出一些假定。所谓的鸭子类型，就是“如果它看起来像只鸭子，叫起来像只鸭子，那它一定就是鸭子。”所以对thenable值的鸭子类型检查就大致类似于这样实现：
```javascript
// promise对象的鸭子类型判断
function promiseDuckCheck(p) {
    if( p!=null && ( typeof p === "object" || typeof p === "function" ) && typeof p.then === "function" ){
        return true
    }else {
        return false;
    }
}

var p = new Promise(function (resolve, reject) {});
console.log(typeof p);              // object
console.log(promiseDuckCheck(p));   // true     鸭子类型检测为Promise值

var o = {
    a: 1
    then: function () {  }
}
//让c对象的[[Prototype]]链到o对象
var c = Object.create(o);
console.log(promiseDuckCheck(o));   // true     虽然为true，但对象o不是Promise值，只是对象拥有then()方法
console.log(promiseDuckCheck(c));   // true     虽然为true，但对象c也不是Promise值，只是原型对象c拥有then()方法
```
这种通过鸭子类型来检测Promise值的方法比较粗糙，也不是很靠谱，比如如果一个对象本身有then()方法或者它的原型对象上有then()方法时，就比较尴尬了，示例如上的对象o和对象C。

promise的强大在于，promise为链式调用，如果不显式返回一个值，就会隐式返回undefined，并且这个promise仍然会以同样方式链接在一起。每个Promise的决议就成了继续下一个步骤的信号：
```javascript
function delay(timer){
    return new Promise(function(resolve, reject){
        setTimeout( resolve, timer );
    })
}

delay(100)
.then(function setp2(val) {
    console.log("setp2 after 100ms");
    return delay(200);
})
.then(function setp3() {
    console.log("setp3 after another 200ms");
})
.then(function setp4() {
    console.log("setp4 next job");
    delay(50);
})
.then(function setp5() {
    console.log("setp5 after another 50ms");
})

//打印结果：
/*
setp2 after 100ms
test3.html:81 setp3 after another 200ms
test3.html:84 setp4 next job
test3.html:88 setp5 after another 50ms
*/
```
当不用定时器，而用更常见的ajax请求时，可以这样：
```javascript
//假设存在工具 ajax(url, callback)
//定义一个工具request(..)，用来构造一个表示ajax()调用完成的promise
function request(url){
    return new Promise(function(resolve, reject){
        // ajax回调应该是这里promise的resolve()函数
        ajax(url, resolve);
    })
}
request("http://some.url.1")
.then(function(response1){
    return request( "http://some.url.2/?v=" + response1 )
})
.then(function(response2){
    return request( "http://some.url.3/?v=" + response2 )
})
.then(function(response3){
    console.log(response3);
})
.catch(function(err){
    console.log(err)
})
```
利用返回Promise的`request()`，通过使用第一个url调用它来创建链接中第一步，并且把返回的promise与第一个then()连接起来。

response1一返回，就可以使用这个值构造第二个url，并发出第二个request()调用。第二个request()的promise返回，以便异步流控制中的第三步等待这个ajax调用完成。第三步重复此行为。直到第四步response3返回并打印该值。

如果在链式调用中，有地方报错就执行reject()抛出错误，并由最后的catch()统一捕获。

在实际开发中，可以像这样通过promise构造ajax链式进行异步流调用。这样好维护也避免写出回调嵌套那样难看又难维护的代码。

----------------------------------------------------------------------------------------------------------------

本篇系统总结ES6 Promise API。

## new Promise(...) 

先看下 new Promise(...) 构造器。

new Promise(...) 构造器的参数必须提供一个函数回调。这个回调是同步的或者立即调用的。这个函数又接受两个函数回调参数，用以支持promise的决议。通常把这两个函数回调参数称为 `resolve()`和`reject()`：
```javascript
var p = new Promise( function(resolve, reject){
    // resolve() 用于决议/完成这个promise
    // reject() 用于拒绝这个 promise
} )
```
reject()就是拒绝这个promise。但是resolve()既可能完成promise，也可能拒绝，要根据传入参数而定。如果传给resolve()的是一个非Promise、非thenable的立即值，这个promise就会用这个值完成。
但是如果传给resolve()的是一个真正的Promise或thenable值，这个值就会被递归展开，并且(要构造的)promise将取用其最终决议值或状态。
```javascript
var p1 = function(num){
    return new Promise(function (resolve, reject) {
        if(num > 10){
            resolve(num);
        }else {
            reject("num 小于等于10");
        }
    })
}

function res() {
    return new Promise(function (resolve, reject) {
        //传入的是Promise值，此时resolve()递归传递出去的值要依据传入的promise值而定，是完成还是拒绝状态，并且(要构造的)promise将取用其最终决议值或状态
        resolve(p1(12));        // 完成状态
        // resolve(p1(6));      // 拒绝状态
    })
}
res()
.then(function (val) {
    console.log(val);
})
.catch(function (err) {
    console.log(err);
})
```

## resolve()和reject()

下面看下resolve()和reject()。

创建一个已被拒绝的Promise的快捷方式是使用Promise.reject()，所以以下两个promise是等价的：
```javascript
var p1 = new Promise(function(resolve, reject){
    reject("Oops!")
})

var p2 = Promise.reject("Oops!")
```
Promise.resolve() 常用于创建一个已完成的Promise，使用方式与Promise.reject()类似。但是Promise.resolve()也会展开thenable值。在这种情况下，返回的Promise采用传入的这个thenable的最终决议值，可能是完成，也可能是拒绝。
```javascript
var fulfilledTh = {
    then: function(cb){ cb(42) }
}
var rejectedTh = {
    then: function(cb, errCb){
        errCb("Oops")
    }
}
var p1 = Promise.resolve(fulfilledTh);
var p2 = Promise.resolve(rejectedTh);

// p1是完成的promise
// p2是拒绝的promise
```
此外，如果传入的是真正的Promise，Promise.resolve()什么都不会做，只会直接把这个值返回。所以对不了解属性的值调用Promise.resolve()，如果它恰好是一个真正的Promise，是不会有额外开销的。
```javascript
// p1(..)的返回值是一个真正的Promise
var p1 = function(num){
    return new Promise(function (resolve, reject) {
        if(num > 10){
            resolve(num)
        }else {
            reject("num 小于等于10")
        }
    })
}
var res = Promise.resolve(p1(12));
res
.then(function(val){
    console.log(val);
})
.catch(function (err) {
    console.log(err);
})
```

## then()和catch()
每个Promise**实例**都有then()和catch()方法，通过这两个方法可以为这个Promise注册完成和拒绝处理函数。当Promise决议之后，会**立即调用**这两个处理函数**之一**，但不会两个都调用，而且总是**异步调用**。

`then()`接受一个**或**两个参数：第一个用于**完成回调**，第二个用于**拒绝回调**。如果两者中的任何一个被省略或者作为非函数值传入的话，就会替换为相应的默认回调。默认完成回调只是把消息传递下去，而默认拒绝回调则只是重新抛出(传播)其接收到的出错原因。

`catch()`只接受一个拒绝回调作为参数，并自动替换默认完成回调。也就是说，其等价于`then(null, rejected)`:
```javascript
p.then(fulfilled);
p.then(fulfilled, rejected);
p.cathc(rejected);      // 或者 p.then(null, rejected);
```
`then()`和`catch()`也会创建并返回一个新的promise，这个promise可以用于实现Promise链式流程控制。如果完成或拒绝回调中抛出异常，返回的promise是被拒绝的。如果任意一个回调返回非Promise、非thenable的立即值，这个值就会被用作返回promise的完成值。如果完成处理函数返回一个promise或者thenable，那么这个值就会被展开，并作用返回promise的决议值。

## Promise.all([...]) 和 Promise.race([...])
ES6 Promise API有两个**静态**辅助函数：`Promise.all([...])`和`Promise.race([...])`。它们都会创建一个Promise作为它们的返回值。这个promise的决议完全由传入的promise数组控制。

对`Promise.all([...])`来说，只有传入的所有promise都完成，返回promise才能完成。如果有任何promise被拒绝，返回的主promise就会立即被拒绝(并且会抛弃任何其他promise的结果)。如果完成的话，就会得到一个数组，其中包含传入的所有promise的完成值。对于拒绝的情况，你只会得到第一个拒绝promise的拒绝理由值。这种模式传统上被称为门，即所有人都到齐了才开门。

对于`Promise.race([...])`来说，只有第一个决议的promise(完成或拒绝)取胜，并且其决议结果成为返回promise的决议。这种模式传统上称为门闩，即第一个到达者打开门闩通过。

```javascript
var p1 = Promise.resolve(42);
var p2 = Promise.resolve("Hello World");
var p3 = Promise.reject("Oops");

//如果有任何promise被拒绝，返回的主promise就会立即被拒绝(并且会抛弃任何其他promise的结果)，你只会得到第一个拒绝promise的拒绝理由值
Promise.all([p1, p2, p3])
.then(function(val){
    console.log(val);
})
.catch(function(err){
    console.log(err);   // Oops
})

// 第一个决议的promise(完成或拒绝)取胜，并且其决议结果成为返回promise的决议
Promise.race([p1, p2, p3])
.then(function(val){
    console.log(val);   // 42
})
.catch(function(err){
    console.log(err);   
})

// 如果完成的话，就会得到一个数组，其中包含传入的所有promise的完成值
Promise.all([p1, p2])
.then(function(val){
    console.log(val);   // [42, Hello World]
})
.catch(function(err){
    console.log(err);   
})
```
注意，如果向`Promise.all([...])`中传入空数组，它会立即完成，但`Promise.race([...])`会挂住，且永远不会决议。
```javascript
// 向`Promise.all([...])`中传入空数组，它会立即完成
Promise.all([])
.then(function(val){
    console.log(val);   // []
})
.catch(function(err){
    console.log(err);
})

// 向`Promise.race([...])`中传入空数组，它会挂住，且永远不会决议
Promise.race([])
.then(function(val){
    console.log(val);   // 不进决议
})
.catch(function(err){
    console.log(err);   // 不进拒绝
})
```

以上就是ES6 Promise API，它们非常直观也很用，对于异步的支持很友好，可以用来重构回调地狱代码，使代码更易于追踪和维护。

--------------------------------------------------------------------------------------------------------------------
本章讨论下Promise使用时的较佳实践。

## 顺序错误处理
Promise的设计局限性有一个让人掉坑的地方，即Promise链中错误容易被无意中默默忽略掉。

由于一个Promise链仅仅是连接到一起的成员Promise，没有把整个链标识为一个个体的实体，这意味着没有外部方法可以用于观察可能发生的错误。

如果构建了一个没有错误处理函数的Promise链，链中任何地方的错误都会在链中一直传播下去，直到被查看(通过在某个步骤注册拒绝处理函数)。可以是在某个步骤的then()中注册拒绝处理函数，也可以是有一个在指向链中最后一个promise的引用处注册拒绝处理函数，这个拒绝处理函数可以得到所有传播过来的错误的通知：
```javascript
// foo() step2()、step3()都是支持promise的工具
var p = foo(42)
        .then(step2())
        .then(step3())

p.catch(handleErrors);
```
p指向的是最后一个promise，即来自调用then(step3())的那个。在上例前半段的promise链中任何一个步骤都没显式处理自身错误，此时可以在p上注册一个拒绝错误处理函数，这样对于链中任何位置出现的任何错误，这个处理函数都会得到通知。

## 传递多个值
根据定义，在Promise中只能有一个完成值或一个拒绝理由，简单情况下这就够了，但在复杂情况下可能就会受限。

方法一：通常的建议是构造一个值封装(比如对象或数组)来保持这样的多个信息。虽然这个方案有效，但如果要在链条每一步都进行这样封装和解封，就显得不那么优雅。

值封装的情况：
```javascript
function get(res) {
    return new Promise(function (resolve, reject) {
                setTimeout(function () {
                    resolve( (3*res) - 1 );
                }, 1000)
            })
}

function foo(x, y) {
    var res = x * y;

    return  get(res)
            .then(function (val) {
                return [res, val];
            })
}

foo(10, 20)
.then(function (val) {
    var a = val[0];
    var b = val[1];

    console.log(a, b);      // 200  599
})
```

方法二：分裂值。

出现如下情况时，可以考虑把问题分解成两个或者更多的Promise来试试：

分裂成两个promise来试试：
```javascript
function get(res) {
    return new Promise(function (resolve, reject) {
                setTimeout(function () {
                    resolve( (3*res) - 1 );
                }, 1000)
            })
}

function foo(x, y) {
    var res = x * y;

    return  [
        Promise.resolve(res),
        get(res)
    ]
}

Promise.all( foo(10, 20) )
.then(function (val) {
    var a = val[0];
    var b = val[1];

    console.log(a, b);      // 200  599
})
```
尽管这种写法从语法角度看相比第一种写法没什么改进，但代码更整洁灵活。

## 单决议
Promise最本质的特征是：Promise只能被决议一次(完成或拒绝)。

在许多异步情况中，只会获取一个值一次，所以这可以工作良好。

但还有很多异步的情况适合另一种模式，即一种类似于事件或数据流的模式。

设想这样的一个场景：要启动一系列异步步骤以响应某种可能多次发生的情况，例如点击事件。看下面的伪代码：
```javascript
// 假设有一个ajax工具 ajax(url, callback)
// request()是一个支持promise的ajax封装
function request(url){
    return new Promise(function(resolve, reject){
        // ajax回调应该是这里promise的resolve()函数
        ajax(url, resolve);
    })
}

// 由于promise只能决议一次，而点击按钮可能会点击多次，所以可以在事件点击处理函数中定义整个Promise链
var btnA = document.getElementById("btnA");
btnA.onclick = function (event) {
    var btnId = event.target.id;

    request("http://some.url.1/?id=" + btnId)
    .then(function(data){
        console.log(data);
    })
}
```
尽管这样将Promise链放在事件处理函数中会显得丑陋，但由于Promise只能决议一次的特性，目前只能先这样放。

总的来说，Promise并没有抛弃回调，只是把回调的安排转交给一个位于我们和其他工具之间的可信任的中介机制。Promise链提供了以顺序的方式表达异步流的一个更好的方法，这有助于大脑更好的组织和维护js代码。